### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by lh11117** [ShenYuhan/python-tools#6]
审核快乐器有bug，生成的视频有时快，有时慢，速度不均匀。。。
自己去看：
链接: https://pan.baidu.com/s/18ZTpxtyYBBDxJhCA8ZJrbQ?pwd=haha 
提取码: haha

**Comment by ShenYuhan** [comment]
参数给一下吧，我这边复现一下看看问题

**Comment by lh11117** [comment]
我这边填的参数是：
图片数量：30
旋转一圈时间：2
视频总时长：600（10分钟）
可是生成的视频只有约4分钟！
这也许是电脑CPU的问题，也有可能是moviepy的问题

**Comment by lh11117** [comment]
顺便再说一下，有时候他会莫名其妙的报错，我明明什么代码都没有修改。。
报错信息：
Traceback (most recent call last):
  File "E:\Downloads\IDM_Download\Zip\python-tools-master\5_rotate_img\main.py", line 223, in generateRotateVideo
    final_video_path = set_video_music(video_mute_path, self.input_audio_file)
  File "E:\Downloads\IDM_Download\Zip\python-tools-master\5_rotate_img\main.py", line 95, in set_video_music
    video_clip = mov.VideoFileClip(video_mute_path)
  File "D:\c++\python\lib\site-packages\moviepy\video\io\VideoFileClip.py", line 88, in __init__
    self.reader = FFMPEG_VideoReader(filename, pix_fmt=pix_fmt,
  File "D:\c++\python\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 35, in __init__
    infos = ffmpeg_parse_infos(filename, print_infos, check_duration,
  File "D:\c++\python\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 270, in ffmpeg_parse_infos
    raise IOError(("MoviePy error: the file %s could not be found!\n"
OSError: MoviePy error: the file D:/文档/下载的音乐\output_file_1675127784.mp4 could not be found!
Please check that you entered the correct path.
麻烦修复一下。
